config/routes.rb
Rails.application.routes.draw do
  resources :movies

 

  

devise_for :users, :skip => [:registrations] 
  as :user do
    get 'register' => 'devise/registrations#new', :as => 'user_registration'
    get 'register' => 'devise/registrations#new', :as => 'new_user_registration'
    post 'register' => 'devise/registrations#create', :as => 'new_user'
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'register' => 'devise/registrations#update', :as => :register
    get 'login', to: 'devise/sessions#new', as: :login 
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :reviews
  root :to => 'movies#index'

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:edit, :update]
  include MoviesHelper


  # GET /movies
  # GET /movies.json
  def index
    #check if there is a param to order movies
    if params.has_key?(:order) && params[:order] == 'date'
      @movies = Movie.order('created_at DESC').all
    elsif params.has_key?(:order) && params[:order] == 'likes'
      @movies = Movie.order('likes DESC').all
    elsif params.has_key?(:order) && params[:order] == 'hates'
      @movies = Movie.order('hates DESC').all
    else   
      @movies = Movie.all
    end

    #check if there is a param to filter by user
    if params.has_key?(:filter)
      @movies = @movies.where('user_id' => params[:filter])
    end
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    #create a movie for the current user
    @movie = current_user.movies.new(movie_params)
    respond_to do |format|
      if @movie.save
        format.html { redirect_to movies_url, notice: 'Movie was successfully created.' }
        format.json { render :index, status: :ok, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :index, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :user_id, :hates, :likes, :image)
    end

    
end

app/helpers/movies_helper.rb
module MoviesHelper

# action to create ajax response hash
def create_ajax_response(params)
	movie = Movie.find(params[:movie_id])
	hash = {:show_like_link => show_review_action(movie, true), 
			:show_hate_link => show_review_action(movie, false), 
			:likes => movie.likes, 
			:hates => movie.hates, 
			:action_label => show_review_label(movie),
			:update_like => update_review(movie, status),
			:update_hate => update_review(movie, status)}
	return hash
end

# action that returns the Unlike/Unhate link
def show_review_label(movie)
	# if user reviewed already check if 'Unlike' or 'Unhate' link
	# else no link
	check = user_already_reviewed(movie)
	if check == 0
	  reviewFound = movie.reviews.where('user_id' => current_user.id).first
	  @show_review_label = '<a href="#" class="delete-review" data-movieid="'+movie.id.to_s+'" data-id="'+reviewFound.id.to_s+'">Unlike</a>'  
	elsif check == 1 
	  reviewFound = movie.reviews.where('user_id' => current_user.id).first
	  @show_review_label = '<a href="#" class="delete-review" data-movieid="'+movie.id.to_s+'" data-id="'+reviewFound.id.to_s+'">Unhate</a>'
	else
	  @show_review_label = ''
	end
	# make string html safe
	@show_review_label.html_safe
end

# action that checks if a user can like or hate a movie
def show_review_action(movie, status)
	check = user_already_reviewed(movie)
	if check == -1
	  @show_review_action = true  
	elsif (check == 0 && status == true) || (check == 1 && status == false) || check == 2
	  @show_review_action = false  
	else
	  @show_review_action = true
	end

end

# action called to check if a review for the movie is already done by the user
def update_review(movie, status)
	check = user_already_reviewed(movie)
	#if none returns 0
	if check == -1
	  @update_review = 0
	#else returns the review id  
	else
	  reviewFound = movie.reviews.where('user_id' => current_user.id).first
	  @update_review = reviewFound.id
	end
end

private

# action to check if a user already reviewed a movie
# return -1 : not even signed in
# 		  0 : liked
# 		  1 : hated
def user_already_reviewed(movie)
  	@user_already_reviewed = -1
  	if user_signed_in? 

	  reviewFound = movie.reviews.where('user_id' => current_user.id).first
	  if reviewFound && reviewFound.status == true
	    @user_already_reviewed = 0
	  elsif reviewFound && reviewFound.status == false
	    @user_already_reviewed = 1
	  elsif movie.user_id == current_user.id
	    @user_already_reviewed = 2
	  end
	end
  	return @user_already_reviewed
end

end

app/views/movies/_form.html.erb
<%= form_for(@movie,  :html => { :multipart => true }) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field fileupload">
    <%= f.file_field :image %>
  </div>

  <div style="clear:both"></div>
  
  <div class="field">
    <%= f.text_field :title , :required => true, :placeholder => "Title" %>
  </div>

  <div style="clear:both"></div>
  
  
  <div class="field textarea-movie col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <%= f.text_area :description, :required => true, :placeholder => "Description" %>
  </div>
  <div class="actions-container">
    <div class="actions">
      <%= f.submit %>
    </div>
    <div class="back-link">
      <%= link_to 'Back', movies_path %>
    </div>
  </div>
<% end %>

app/views/movies/_toolbar.html.erb
<div class="container">
<div class="toolbar">
    <div class="sort-by">
      Sort by:
      <% if params.has_key?(:filter) %>
        <%= link_to "Likes", {:controller => "movies", :action => "index", :order => 'likes', :filter => params[:filter] }%>
        |
        <%= link_to "Hates", {:controller => "movies", :action => "index", :order => 'hates', :filter => params[:filter] }%>
        |
        <%= link_to "Date", {:controller => "movies", :action => "index", :order => 'date', :filter => params[:filter] }%>
      <% else %>
        <%= link_to "Likes", {:controller => "movies", :action => "index", :order => 'likes' }%>
        |
        <%= link_to "Hates", {:controller => "movies", :action => "index", :order => 'hates' }%>
        |
        <%= link_to "Date", {:controller => "movies", :action => "index", :order => 'date' }%>
      <% end %>
      
    </div>

    <% if params.has_key?(:filter) %>
      
      <div class="show-all-movies">
        <% if params.has_key?(:order) %>
          <%= link_to "All movies", {:controller => "movies", :action => "index", :order => params[:order] }%>
        <% else %>
          <%= link_to "All movies", {:controller => "movies", :action => "index" }%>
        <% end %>
      </div>
      <span class="separator">|</span>
    <% end %>
    <% if user_signed_in? %>
      <div class="new-movie-button"><%= link_to "New Movie", new_movie_path %></div>
    <% end %>
  </div>
</div>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>
  <%= render 'toolbar' %>
  <div class="container">
            
  <ul class=" movie-list">
    <% @movies.each do |movie| %>
      <li class="movie-item col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <div id="reviewMovie<%=movie.id%>" class="movie-already-reviewed"><%= show_review_label(movie) %></div>
          <div class="movie-image"><%= image_tag movie.image.url(:medium), :class=>'image-responsive' %></div>

          <div class="movie-header">
           
            <span class="movie-title"><%= movie.title %></span>
            <div class="movie-post-details">
                <% user_name = (user_signed_in? && movie.user_id == current_user.id) ? "You" : movie.user.name %>
                <div class="movie-posted-by">
                  <%= link_to user_name, {:controller => "movies", :action => "index", :filter => movie.user_id} %>
                </div>
                <div class="movie-time-ago"><%= time_ago_in_words(movie.created_at - 1).gsub('about','')+" ago" %></div>

                <button type="button" class="more-info-btn btn btn-primary btn-sm fa fa-info-circle" data-toggle="modal" data-target="#movie-description-<%=movie.id%>"> More Info</button>
            </div>
          </div>

          

          <% #if user_signed_in? %>
            <div class="movie-reviews-details">
              <div class="movie-likes">
                <% if user_signed_in? && show_review_action(movie, true) %>
                  <a id="linkLike<%=movie.id%>" class="reviewMovie" data-id="<%=movie.id%>" data-status="true" data-method="<%=update_review(movie, true)%>" href="#">
                <% end %>
                <span class="fa fa-heart review-icon" id="likesContainer<%=movie.id%>">
                    <span class="like-counter" id="likeReview<%=movie.id%>"><%= movie.likes %>
                    </span>
                  </span>
                <% if user_signed_in? && show_review_action(movie, true) %>
                  </a>
                <% end %>
              </div> 
              <div class="movie-hates">
                <% if user_signed_in? && show_review_action(movie, false) %>
                  <a id="linkHate<%=movie.id%>"  class="reviewMovie" data-id="<%=movie.id%>" data-status="false" data-method="<%=update_review(movie, false)%>" href="#">
                <% end %>
                <span id="hatesContainer<%=movie.id%>" class="fa fa-flash review-icon">
                <span class="hate-counter" id="hateReview<%=movie.id%>"><%= movie.hates %></span>
              </span>
                <% if user_signed_in? &&  show_review_action(movie, false) %>
                  </a>
                <% end %>
              </div>
            </div>
          <% #end %>
          
          <div class="modal fade bs-example-modal-lg" tabindex="-1" role="document" id="movie-description-<%=movie.id%>" aria-labelledby="<%=movie.title%>">

              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="myModalLabel"><%=movie.title%></h4>
                </div>
                <div class="modal-body">
                  
                  <div class="image-modal">
                    <%= image_tag movie.image.url(:medium) %>
                  </div>
                  <div class="description-modal">
                    <%= movie.description %>
                  </div>
                </div>
                <div class="modal-footer">
                  
                </div>
            </div>

          </div>
      </li>
        
    <% end %>

</ul>
</div>

app/views/movies/new.html.erb
<div class="container movie-creation">
<div class="user-register-header">New Movie</div>

<%= render 'form' %>


</div>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @movie.image.url(:thumb) %>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @movie.user.email %>
</p>

<%= link_to 'Back', movies_path %>