config/routes.rb
Rails.application.routes.draw do
  resources :movies

 

  

devise_for :users, :skip => [:registrations] 
  as :user do
    get 'register' => 'devise/registrations#new', :as => 'user_registration'
    get 'register' => 'devise/registrations#new', :as => 'new_user_registration'
    post 'register' => 'devise/registrations#create', :as => 'new_user'
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'register' => 'devise/registrations#update', :as => :register
    get 'login', to: 'devise/sessions#new', as: :login 
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :reviews
  root :to => 'movies#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieRama</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>

<section class="header">
<div class="logo"><%= link_to "MovieRama", "/" %></div>
<a class="fa fa-user user-menu"> </a>
<div class="user-menu-container">
	<div class="triangle"></div>
	<ul class="user-header">
		<% if user_signed_in? %>
			<li><%= link_to current_user.name, edit_user_registration_path %></li>
			<li class="last-item"><%= link_to 'Log out', logout_path %></li>
		<% else %>
			<li><%= link_to "Register", register_path %> </li>
			<li class="last-item"><%= link_to "Log in", login_path %></li>
		<% end %>	
	</ul>
</div>
</section>

<section class="main">
<%= yield %>
</section>
</body>
</html>